global:
  scrape_interval:     15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
        - targets: ["prometheus:9090"]
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]
  - job_name: ingest
    static_configs:
      - targets: ["ingest:8001"]
  - job_name: ingestion-workers
    static_configs:
      - targets: ["windy-worker:8002"]
        labels:
          source_network: win
      - targets: ["fintraffic-worker:8003"]
        labels:
          source_network: fin
      - targets: ["skaping-worker:8004"]
        labels:
          source_network: ska
  - job_name: windy-worker-host-benchmark
    static_configs:
      - targets: ["host.docker.internal:8013"]
  - job_name: fintraffic-worker-host-benchmark
    static_configs:
      - targets: ["host.docker.internal:8014"]
  - job_name: skaping-worker-host-benchmark
    static_configs:
      - targets: ["host.docker.internal:8015"]
  - job_name: mqtt-exporter
    static_configs:
      - targets: ["mosquitto-exporter:9234"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
